name: Tests

on: [pull_request]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive

      - name: Run linter
        run: yarn lint
